---
- name: Install containerd.io package for Debian family
  apt:
    update_cache: true
    name:
      - containerd.io={{ containerd_defaults.containerd_version }}-*  # provides "runc"
    state: present
    allow_downgrade: true
  register: result
  retries: 60
  delay: 30
  until: result is succeeded
